sonar.projectKey=tenderhack
sonar.projectName=TenderHack Smart Search
sonar.projectVersion=1.0

# Sources
sonar.sources=backend/app,frontend/src
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/dist/**,**/*.pdf,**/*.csv,**/*.7z

# Python
sonar.python.version=3.12

# JavaScript/JSX
sonar.javascript.file.suffixes=.js,.jsx

# Encoding
sonar.sourceEncoding=UTF-8
